name: Android APK Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Klonla
        uses: actions/checkout@v4

      - name: Java Kurulumu (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Gradle Wrapper Oluştur ve APK Derle
        run: |
          gradle wrapper
          ./gradlew assembleRelease -x lint -x lintVitalRelease -Dxlint=ignore -Dlint.skip=true -Pandroid.experimental.disableCompileSdkChecks=true

      - name: APK Dosyasını Çıktı Olarak Yükle
        uses: actions/upload-artifact@v4
        with:
          name: screen-recorder-apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
